### ISSUE TITLE
No "Welcome to GitHub Version" startup loc on the buttons.

### ISSUE THREAD

**Issue by WorldMapperusV** [team-EoaNB-Redux/EoaNBR#1]
**Description:**
When the startup display for the "Welcome to GitHub Version" of the mod appears, there is no loc on the buttons.

**Branch:**
Main

**Image:**
![image](https://user-images.githubusercontent.com/70860419/188325403-05e1c0d0-f0e1-426a-8bb3-b37b57d7cd30.png)

**Comment by Energywelder** [comment]
Fixed
